"""Init tables fresh

Revision ID: 784ba807a1cd
Revises: 
Create Date: 2026-01-29 16:14:40.898925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784ba807a1cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog_db'
    )
    op.create_index(op.f('ix_blog_db_posts_author_id'), 'posts', ['author_id'], unique=False, schema='blog_db')
    op.create_index(op.f('ix_blog_db_posts_id'), 'posts', ['id'], unique=False, schema='blog_db')
    op.create_index(op.f('ix_blog_db_posts_slug'), 'posts', ['slug'], unique=True, schema='blog_db')
    op.create_index(op.f('ix_blog_db_posts_title'), 'posts', ['title'], unique=False, schema='blog_db')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='blog_db'
    )
    op.create_index(op.f('ix_blog_db_users_email'), 'users', ['email'], unique=True, schema='blog_db')
    op.create_index(op.f('ix_blog_db_users_id'), 'users', ['id'], unique=False, schema='blog_db')
    op.create_index(op.f('ix_blog_db_users_username'), 'users', ['username'], unique=True, schema='blog_db')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_db_users_username'), table_name='users', schema='blog_db')
    op.drop_index(op.f('ix_blog_db_users_id'), table_name='users', schema='blog_db')
    op.drop_index(op.f('ix_blog_db_users_email'), table_name='users', schema='blog_db')
    op.drop_table('users', schema='blog_db')
    op.drop_index(op.f('ix_blog_db_posts_title'), table_name='posts', schema='blog_db')
    op.drop_index(op.f('ix_blog_db_posts_slug'), table_name='posts', schema='blog_db')
    op.drop_index(op.f('ix_blog_db_posts_id'), table_name='posts', schema='blog_db')
    op.drop_index(op.f('ix_blog_db_posts_author_id'), table_name='posts', schema='blog_db')
    op.drop_table('posts', schema='blog_db')
    # ### end Alembic commands ###
